# -*- coding: utf-8 -*-
"""Rosalind DNA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10eV9T0lw5AJn5ATf9n86x1dmJbJJOixT
"""

# http://rosalind.info/problems/dna/

dna_str = "CCAACCAGGTACCCTTTTTAAAAT"

print(dna_str.count('A'), end = " ")
print(dna_str.count('C'), end = " ")
print(dna_str.count('G'), end = " ")
print(dna_str.count('T'), end = " ")